version: '3'

services:
  alert_bot:
    container_name: alert_bot
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      TZ: "Europe/Kyiv"
    networks:
      - shared_network
    depends_on:
      - raid_api

networks:
  shared_network:
    external: true